[PHP]
; maximum execution time
max_execution_time = 300

; maximum input parsing time
max_input_time = 300

; maximum memory per script
memory_limit = 256M

; maximum upload file size
upload_max_filesize = 64M

; maximum number of files that can be uploaded at once
max_file_uploads = 20

; maximum POST data size
post_max_size = 100M

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 4000
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1